### ISSUE TITLE
bug: RecursiveCreateContractsCreate4Contracts.json failed with nonce

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#141]
### Kakarot 

kakarot_sha = 7686fbf022d99ce01927eb488ad59f0a0ec7ce5d

### Bug
in stSolidityTest, RecursiveCreateContractsCreate4Contracts.json
```
[!] Case /Users/eliastazartes/code/kkrt-labs/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stSolidityTest/RecursiveCreateContractsCreate4Contracts.json failed:
RecursiveCreateContractsCreate4Contracts_d0g0v0_Shanghai expected nonce 0x0000000000000000000000000000000000000000000000000000000000000003 for 0x095e7baea6a6c7c4c2dfeb977efac326af552d87, got 0x0000000000000000000000000000000000000000000000000000000000000000
```

### to reproduce
run stSolidityTest
unskip RecursiveCreateContractsCreate4Contracts.json

**Comment by jobez** [comment]
I believe most nonce issues are related to this last task on this epic: https://github.com/kkrt-labs/ef-tests/issues/45. Working on a pr rn.

**Comment by Eikix** [comment]
> I believe most nonce issues are related to this last task on this epic: #45. Working on a pr rn.

nice catch!
