### ISSUE TITLE
feat: load skipped suites from yaml file 

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/ef-tests#146]
# Feature Request

**Describe the Feature Request**

Currently our skipped logic is a long match statement:

https://github.com/kkrt-labs/ef-tests/blob/fdd6c978d5ad17980b930633852c5b08e6f8c5ec/crates/ef-testing/src/models/case.rs#L69-L111

**Describe Preferred Solution**

It would be better to edit/remove skips from one yaml file that is then loaded in the skip logic, to manage the day by day growing size of the skips. 

- Each entry can specify if it is a single suite name or a regex.
- all suite names would be aggregated and a given suite would be checked if it either was included in the set of suite names or matches a set of regexes

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?** Yes
/ No _(Help can be provided if you need assistance submitting a PR)_

**Comment by Eikix** [comment]
what is best? yaml, json, toml?
