### ISSUE TITLE
bug: create2InitCodeSizeLimit.json / create2InitCodeSizeLimit_d0g0v0_Shanghai failing due to wrong post state

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/ef-tests#155]
# Bug Report

**Kakarot version:**

Kakarot sha 7686fbf022d99ce01927eb488ad59f0a0ec7ce5d

**Current behavior:**

When running stEIP3860-limitmeterinitcode

```
[!] Case /workspaces/kkrt-ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/Shanghai/stEIP3860-limitmeterinitcode/create2InitCodeSizeLimit.json failed:
create2InitCodeSizeLimit_d0g0v0_Shanghai expected empty post state, got Account {
    balance: JsonU256(
        0x0_U256,
    ),
    code: Bytes(0x600a80600080396000f3),
    nonce: JsonU256(
        0x0000000000000000000000000000000000000000000000000000000000000001_U256,
    ),
    storage: {},
}
```

**Expected behavior:**

empty post state

**Steps to reproduce:**

Unskip `| "create2InitCodeSizeLimit.json"` in case.rs and run ef-tests

**Comment by greged93** [comment]
moved to #523. With the removal of the resource limit for the runner, the test still fails but due to this line in the bytecode of one of the called contracts:
```yul
let gas_before := gas()
let create_result := create2(0, 0, initcode_size, 0xdeadbeef)
sstore(10, sub(gas_before, gas()))
```
Since the GAS opcode does not currently work correctly, this cause a diff in the storage at slot 0x0a.
