### ISSUE TITLE
bug: stReturnDataTest state related errors

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/ef-tests#320]
# State errors: 

## revertRetDataSize.json

**Test path:**
GeneralStateTests/stReturnDataTest/revertRetDataSize.json

**Error:**  
revertRetDataSize_d10g0v0_Shanghai expected empty post state, got Account {
    balance: JsonU256(
        0x0_U256,
    ),
    code: Bytes(0x),
    nonce: JsonU256(
        0x0000000000000000000000000000000000000000000000000000000000000001_U256,
    ),
    storage: {},
}

**Comment by khaeljy** [comment]
Perhaps you could link the issues relating to `stReturnDataTest` in an epic issue?
