### ISSUE TITLE
bug: incorrect gas accounting for GAS opcode

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#36]
# Bug Report

**Kakarot version:** [ee6458a](https://github.com/kkrt-labs/kakarot/commit/ee6458a7089f169334a7dba9665bcc5551507762)

**Current behavior:**
The gas accounting for the following suite of opcodes is incorrect:
```
PUSH5 0xffffffffff
PUSH1 0x00
MSTORE
PUSH2 0xeeee
PUSH1 0x5a
MSTORE
GAS
PUSH1 0x00
SSTORE
STOP
```

**Expected behavior:**
Expected gas output should be `0x4b1457b`, the current implementation calculates `0x1310bb`. Main difference comes from the fact that we do not apply the [gas cap calculation](https://ethereum.github.io/yellowpaper/paper.pdf#page=37) for a call opcode.

**Steps to reproduce:**

- clone ef-tests: https://github.com/kkrt-labs/ef-tests
- run 
```
make setup
make fetch-dump
make target=gas_d0g0v0_Shanghai ef-test
```
Failing output should be:
```
[!] Case ~/code/rust/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/VMTests/vmIOandFlowOperations/gas.json failed (description: gas): Test failed: failed test gas_d0g0v0_Shanghai: expected storage value 0x0000000000000000000000000000000000000000000000000000000004b1457b, got 0x00000000000000000000000000000000000000000000000000000000001310bb
```

**Comment by Eikix** [comment]
After reading the specification, I see the `GAS` opcode returns:
```

Get the amount of available gas, including the corresponding reduction for the cost of this instruction
--
 

<br class="Apple-interchange-newline">
```
