### ISSUE TITLE
bug: Gas wrong accounting - mismatch expected storage value

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/ef-tests#37]
# Bug Report

**Kakarot version:** https://github.com/kkrt-labs/kakarot/commit/0c6e7a62a38e973ad6ceebfbf648841749ffe0ee

**Current behavior:** 
Tests for SSTORE provided by ethereum/tests fails during the following tests when transactions are expected to pass 

Test Name | Actual | Expected
-- | -- | --
|sstoreGas_d0g0v0_Shanghai | 0x0000000000000000000000000000000000000000000000000000000000000064 | 0x0000000000000000000000000000000000000000000000000000000000001388

Instead they are all failing with mismatch on expected storage value

**Expected behavior:**
Test should pass.

**Steps to reproduce:**

- clone ef-tests: https://github.com/kkrt-labs/ef-tests
- generate katana dump of kakarot system and move the .katana folder to your ef-tests directory
- run the following

```shell
make setup
make target=sstoreGas_d0g0v0_Shanghai ef-test
```

Failing output should be:
```Python
Test failed: failed test sstoreGas_d0g0v0_Shanghai: expected storage value 0x0000000000000000000000000000000000000000000000000000000000001388, got 0x0000000000000000000000000000000000000000000000000000000000000064
```

**Comment by ftupas** [comment]
This is `GAS` related issue, see https://github.com/kkrt-labs/ef-tests/issues/36

**Comment by Eikix** [comment]
Known gas issue
