### ISSUE TITLE
bug: `mem64kb_singleByte-32.json` is failing

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/ef-tests#40]
# Bug Report

**Kakarot version:** [ee6458a](https://github.com/kkrt-labs/kakarot/commit/ee6458a7089f169334a7dba9665bcc5551507762)

**Current behavior:**

When we run the ef-tests for [stMemoryTests](https://github.com/ethereum/tests/tree/9b00b68593f5869eb51a6659e1cc983e875e616b/BlockchainTests/GeneralStateTests/stMemoryTest) ( #26 ), we get a failure. 

The failure:
```shell
[!] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte-32.json failed (description: mem64kb_singleByte-32): Test failed: failed test mem64kb_singleByte-32_d0g0v0_Shanghai: expected storage value 0x000000000000000000000000000000000000000000000000000000000000f9e0, got 0x0000000000000000000000000000000000000000000000000000000000000000
```
It is expecting a storage slot `0` for the contract to have the value `0xf9e0` but it is instead `0x0`.

**Expected behavior:**

This should pass and the value at the storage slot shout be  `0xf9e0`.

**Steps to reproduce:**

- `make setup`
-  `make fetch-dump`
- change [this](https://github.com/kkrt-labs/ef-tests/blob/f37901bf975b33cc631851ae1e3c88f59f6e85af/crates/ef-testing/tests/tests.rs#L31) line of code with the following code : `blockchain_tests!(memory_tests, stMemoryTest);`
- run `make target=mem64kb_singleByte-32 ef-test`

**Other information:**

#### What is the test doing?

The [bytecode](https://github.com/ethereum/tests/blob/9b00b68593f5869eb51a6659e1cc983e875e616b/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte-32.json#L100C9-L100C9) for the test contract is: "0x602a61f9df535960005500"

When decontructed, it means:
<img width="827" alt="image" src="https://github.com/kkrt-labs/ef-tests/assets/41180869/651ad6d0-926e-4528-96f1-29d89bdc89d5">

i.e:
- Load value `0x2a` at the memory location `0xf9df`
- Then push memory size to the stack which is `0xf9e0`
- Then store this value at key `0` of the constract

Hence, at the end of the execution, the storage slot `0` should have the value `0xf9e0`
<img width="752" alt="image" src="https://github.com/kkrt-labs/ef-tests/assets/41180869/5045d4ba-3127-4df5-8585-72f6da3b13f8">

#### The storage value is correct when investigated with the python test sequencer.

i.e, when we create a file `test_mload_64kb.py` [here](https://github.com/kkrt-labs/kakarot/tree/main/tests/integration/solidity_contracts/EFTests), with the following code:
```python
import logging

import pytest
from starkware.starknet.testing.contract import StarknetContract

from tests.utils.helpers import hex_string_to_bytes_array

logger = logging.getLogger()


@pytest.mark.asyncio
@pytest.mark.EF_TEST
class TestMemory:
    async def test_mem64kb_singleByte_32_d0g0v0_Shanghai(
        self,
        owner,
        create_account_with_bytecode,
        kakarot: StarknetContract,
    ):
        print("starting the tests")
        called_contract = await create_account_with_bytecode("0x602a61f9df535960005500")

        res = await kakarot.eth_send_transaction(
            origin=int(owner.address, 16),
            to=int(called_contract.evm_contract_address, 16),
            gas_limit=1_000_000,
            gas_price=0,
            value=10,
            data=[]
        ).execute(caller_address=owner.starknet_address)
        val = await called_contract.storage((0,0)).call()
        print("val is--->", val)

```

Then execute the code with:
```shell
pytest kakarot/tests/integration/solidity_contracts/EFTests/test_mload_64kb.py -s
```
You will see that you get a log, saying:
```
val is---> StarknetCallInfo(result=storage_return_type(value=Uint256(low=63968, high=0)), call_info=FunctionInvocation(caller_address=0, contract_address=20274160671854875183514026769453059905460755363601376547453404479020866133, calldata=[0, 0],.......
```

Here is the low value is `63968`, which in hex will `0xf9e0`, hence, it means the value on the python sequencer is being set correctly! But this seems to be not the case when it is running on Katana.

**Comment by greged93** [comment]
The bug was due to this piece of code that was present on the commit [ee6458a](https://github.com/kkrt-labs/kakarot/commit/ee6458a7089f169334a7dba9665bcc5551507762) used in the katana dump for kakarot:
```
//      TODO: add check that target contract does not exist or has empty bytecode
        if (data_len == 0) {
            let (return_data) = alloc();
            return (0, return_data);
        }
```
This caused the transaction to return early, even though a transaction with empty data can trigger execution on the called contract side.

However, the proposed python test by @bajpai244 was performed on the latest commit of the Kakarot repository, where the above lines of codes were removed, causing the python test to pass.

Proposed mitigations:
- Log in the ef-tests runner the used commit for Kakarot.
- Increase the priority on the merging of the dependabot PRs on the RPC, which will allow to keep up to date dumps.
- Add script that check the current commit of the artifact dump and checks against the commit of the current dump.

**Comment by bajpai244** [comment]
I think we can close this now, lemme know if you think otherwise @greged93

**Comment by greged93** [comment]
close with improvement brought in https://github.com/kkrt-labs/ef-tests/pull/54
