### ISSUE TITLE
Update post-state assertion for nonce depending on type of account

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/ef-tests#45]
## Current Behavior

In our ef-test when we do [`handle_post_state`](https://github.com/kkrt-labs/ef-tests/blob/a98f476f526ea71ffe08074fa6f83719edd40e8a/crates/ef-testing/src/models/case.rs#L91), we do the following:
- take the state from storage
- assert that the expected post-state is the same with the actual state
- this means we are asserting for the nonce on the protocol-level for the evm accounts 

https://github.com/kkrt-labs/ef-tests/blob/a98f476f526ea71ffe08074fa6f83719edd40e8a/crates/ef-testing/src/models/case.rs#L150-L168

## Desired Behavior
For contract accounts, we need to assert on the managed nonce instead of the native nonce.

We'll need to do:
1. We need to merge this pr that will https://github.com/kkrt-labs/kakarot/pull/716
2. Create the pr for https://github.com/kkrt-labs/kakarot-rpc/issues/502
3. Update the assertion so that when we do it for contract accounts, we will get the nonce from [this](https://github.com/kkrt-labs/kakarot-rpc/blob/a12a56090c1bf6b81295527954d60d3671d94db2/crates/core/src/client/mod.rs#L318) instead

**Comment by Eikix** [comment]
What is the status of this?
