### ISSUE TITLE
bug: update post state assertion for storage

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#475]
### Current behavior
The post state assertion is done based on the json files given by ethereum test repo. An example is given below:
```json
"postState" : {
    "0x095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
        "balance" : "0x0ba1a9ce0ba1a9cf",
        "code" : "0x6004356000526024356020525a60405260005160020a505a606052602051606051604051030360005500",
        "nonce" : "0x00",
        *"storage" : {*
        *}*
    },
    "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
        "balance" : "0x0ba1a9ce0b9e57f5",
        "code" : "0x",
        "nonce" : "0x01",
        "storage" : {
        }
    }
"pre" : {
    "0x095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
        "balance" : "0x0ba1a9ce0ba1a9ce",
        "code" : "0x6004356000526024356020525a60405260005160020a505a606052602051606051604051030360005500",
        "nonce" : "0x00",
        *"storage" : {*
            *"0x00" : "0x60a7"*
        *}*
    },
    "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
        "balance" : "0x0ba1a9ce0ba1a9ce",
        "code" : "0x",
        "nonce" : "0x00",
        "storage" : {
        }
    }
```

An issue arises when the pre state of a contract contains a value in storage, and that value is "wiped" by the test (meaning written to 0). The post state will not indicate that the new storage at key "0x0" should be "0x0" but just an empty storage. 

### Expected behavior

Test runner should be able to calculate the difference between pre and post state and check these value accordingly.

### Steps to reproduce

Check out PR 473 `gh pr checkout 473`.
Run `target=gasCostExp_d4g0v0_Shanghai make ef-test`
Test will fail with
```
[!] Case /Users/greg/code/rust/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stEIP150singleCodeGasPrices/gasCostExp.json failed:
balance mismatch for 0x095e7baea6a6c7c4c2dfeb977efac326af552d87: expected 0x0000000000000000000000000000000000000000000000000ba1a9ce0ba1a9cf, got 0x0000000000000000000000000000000000000000000000000ba1a9ce0ba1a9ce
thread 'blockchain_tests::st_eip150single_code_gas_prices' panicked at 'Some tests failed (see above)', crates/ef-testing/src/models/result.rs:37:5
```
This is due to the fact that the transaction passed, and a value transfer is supposed to happen, but in our case the transaction fails and no transfer of value takes place. However, this test used to base due to the fact that we don't check a storage diff but just the post storage state.

**Comment by Eikix** [comment]
I'm not sure I understand what should be done?

Since:
- At init, the runner places all the EF-tests pre-state values inside storage
- At end of the tx, the runner checks that all the post state is equal to the EF-tests post-state values

What is the required modification?

**Comment by Eikix** [comment]
Looking into it rn
