### ISSUE TITLE
bug: no gas accounting for STATICCALL

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/ef-tests#577]
### Kakarot version

```
stStaticCall::test_static_InternalCallHittingGasLimit_d0g0v0_Shanghai
stStaticCall::test_static_InternalCallHittingGasLimit2_d0g0v0_Shanghai
```

where passing first when the Cairo VM reverted with out of resources, and are now failing because only some opcodes generate OOG.

This test is summarized as 
- `a` calls `b` with ~45k gas
- `b` STATICCALL `c` with 25k gas and revert with OOG
- `a` should revert as well because of OOG when including the cost of the STATICCALL

Currently `a` doesn't revert because STATICCALL is "free".

**Comment by greged93** [comment]
moved to #550
