### ISSUE TITLE
Improve post state assertion

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#6]
Current test as a rough post state assertion. Add helpers in order to have a clean and multi test compatible assertion.

**Comment by Eikix** [comment]
What is the status of this @greged93?

**Comment by greged93** [comment]
I think we can improve the post state, it's still quite heavy. Maybe instead of a very functional implementation we have right, we should look at having a struct implements helper functions. I think we can already clean once we have the test sequencer. Let's keep this open for now and see the cleanliness of the code after adding the new sequencer.
