### ISSUE TITLE
feat: remove distinction between eoa_class and contract_account_classs

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/ef-tests#691]
## Feature Request

They've been merged in the KKT0 codebase, and thus it doesn't make sense to differentiate them. They have the exact same behavior, and thus the runner should not even be aware of these concepts.}

Account documentation: https://github.com/kkrt-labs/kakarot/blob/main/docs/general/accounts.md

Actions:
- KakarotEnvironment struct: remove `eoa_class_hash` and `contract_account_class_hash` for a field `account_contract_class_hash`
- KakarotAccount: remove `account_type` field and all of its usages
- Identify all tags `//TODO` related to EOA / CA and take the appropriate action, which is often just simply removing the if-else condition

**Comment by enitrat** [comment]
This now applies as well for SSJ

For example in the makefile and in the codebase, the name of the classes will need to be modified accordingly.

**Comment by Gerson2102** [comment]
Hello, maybe i can help in this one :)

**Comment by Gerson2102** [comment]
> @Gerson2102 go ahead!

I just cloned the repo, amd there is some errors.
