### ISSUE TITLE
feat: make pre-release for ef-tests

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/ef-tests#75]
# Feature Request

We should be building and releasing pre-release of ef-tests runner, so that they can be consumed on CI

**Describe Preferred Solution**

- Add a job on the CI to release binaries for ef-tests runner.

**Additional Context**

The requirement for it as of now comes from [here](https://github.com/kkrt-labs/kakarot/issues/730).

**If the feature request is approved, would you be willing to submit a PR?**
yes 🥕

**Comment by Eikix** [comment]
Adding the low priority label to the issue for now, as you're moving forward with the clone and build from source approach for now.
