### ISSUE TITLE
bug: Gas wrong accounting - mismatch expected storage value in evm contract account

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/ef-tests#78]
# Bug Report

**Kakarot version:** https://github.com/kkrt-labs/kakarot/commit/44dabfcab05a87f85bcfe0a457809059d11d83fb

**Current behavior:** 
Tests for SLOAD provided by ethereum/tests fails during the following tests when transactions are expected to pass 

Test Name | Actual | Expected
-- | -- | --
|sloadGasCost_d0g0v0_Shanghai | 0x0000000000000000000000000000000000000000000000000000000000000064 | 0x0000000000000000000000000000000000000000000000000000000000000834

Instead they are all failing with mismatch on expected storage value

**Expected behavior:**
Test should pass.

**Steps to reproduce:**

- clone ef-tests: https://github.com/kkrt-labs/ef-tests
- generate katana dump of kakarot system and move the .katana folder to your ef-tests directory
- run the following

```shell
make setup
make target=sstoreGas_d0g0v0_Shanghai ef-test
```

Failing output should be:
```Rust
[!] Case /Users/fredtupas/kkrt-labs/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stSLoadTest/sloadGasCost.json failed:
sloadGasCost_d0g0v0_Shanghai expected storage value 0x0000000000000000000000000000000000000000000000000000000000000834 for 0x1000000000000000000000000000000000000000, got 0x0000000000000000000000000000000000000000000000000000000000000064
```

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/732
```

**Comment by ftupas** [comment]
Same issue with https://github.com/kkrt-labs/ef-tests/issues/37, might be related

**Comment by Eikix** [comment]
Known gas bug
