### ISSUE TITLE
epic: remove the kakarot-rpc dependency

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#97]
This epic issue will track the different issues that need to be fulfilled in order to remove the `kakarot-rpc` dependancy from ef-tests.

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/98
- [ ] https://github.com/kkrt-labs/ef-tests/issues/99
```

**Comment by Eikix** [comment]
What is the status of this? Do we need to slightly rename/rework this epic?

**Comment by greged93** [comment]
Might, let's sync with @ClementWalter, I think his main issue was to have a dependency on RPC, but when we refactor the RPC it will just be an SDK. Could we keep open until that refactor?
