### ISSUE TITLE
Remove hive-utils dependency

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#98]
The project currently depends on hive-utils for the below functions:
- `compute_starknet_address`: move to a util folder in ef-tests.
- `genesis_set_bytecode`, `genesis_set_storage_kakarot_contract_account`, `genesis_approve_kakarot`, `genesis_fund_starknet_address`: replace in ef-tests with types wrapper (around Bytes, Account, Balance,...) and define a StoreStarknet trait which consumes the type in order to return a `Vec<(K, V)>`, where K (key) and V (value) are generics to the trait.

And the below types: 
- `ContractAddress`, `StorageKey` and `StorageValue`: make a type alias in ef-tests.

**Comment by jobez** [comment]
great issue!

**Comment by Eikix** [comment]
concerning first point, I suggest we plan a great refactor of the kakarot-rpc repository.

1. change the scope of the kakarot-rpc repository. it's a de-facto sdk for kakarot. rename the kakarot-rpc to kakarot-rust. it will eventually contain a `kakarot-sdk` crate, which contains all our runtime utils, a `test-utils` crate for test-utils, and a `eth-rpc` crate for the eth-rpc content.
thus, i think compute_starknet_address should live in the `kakarot-sdk` crate, all our test-utils in test-utils, as @bajpai244 is refactoring.

2. good idea for the trait! i completely agree, where do you think it should live? in the ef-tests repo? what if it's re-used in hive? should it be rather under test-utils?

**Comment by Eikix** [comment]
What is the status of this? since we now depending on test-utils, is this fine?

**Comment by greged93** [comment]
I guess we could leave it, but also we had an idea for the test sequencer for ef-tests, where we would wrap it into a EvmSequencer, and have the helpers implemented on this, so will be cleaner. I think we can keep this open and recheck the status after sequencer is done, so maybe end of the week?

**Comment by Eikix** [comment]
What is the status of this?

**Comment by greged93** [comment]
can be closed!
